---
- name: Create Linux VM in vSphere
  hosts: localhost
  user: root
  become_method: sudo
#  serial: 50
  gather_facts: no

  vars_files: 
    - vars/main.yml
   
  tasks:
    - import_tasks: createvm.yml
      when: createvm is defined
 
    - name: Tower CLI add host
      tower_host:
        tower_host: 127.0.0.1
        tower_username: '{{tower_user}}'
        tower_password: '{{tower_password}}'
        validate_certs: no
        inventory: 'Provisioned Hosts'
        name: '{{inventory_hostname}}'
        variables: 
          ansible_user: "root"
          ansible_host: "{{ip_address}}"
     
            
- name: Customize VM
  hosts: "{{inventory_hostname}}:!localhost"  
  user: root
  become_method: sudo
  gather_facts: no
  
  vars_files:
    - vars/main.yml
  
  tasks:
  
    - setup:
      tags: always

    - include: "{{ ansible_system }}/{{ ansible_distribution }}/v{{ ansible_distribution_major_version }}/main.yml"
